name: Update main from dev

on:
  push:
    branches:
      - 47-job-update-main
  schedule:
    - cron: "0 */8 * * *" # every 8 hours
  workflow_dispatch: # manual trigger

jobs:
  force-update-main:
    runs-on: ubuntu-latest
    if: github.repository == 'MSc1-Epitech2025/Time_manager-TD_Epitech'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.SCHOOL }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: git checkout main

      - name: Force reset main to dev
        run: |
          git reset --hard origin/dev
          git push origin main --force
